[SETTINGS]
defaultpath = D:\g\dev\csharp\mamba.TorchDiscordSync\Dependencies
; filterkeywords = Torch,Sandbox,VRage,SpaceEngineers,Discord
filterkeywords = Discord
logdir = .inspect
logbasename = inspect_results
vscodepath = c:\dev\VSCode\bin\code.cmd

